// Central English copy for the salon sub-site. Future i18n swaps happen here.
export const SALON_COPY = {
  brand: "Salon Catalogue",
  tagline: "Salon supplies in Eswatini",
  categories: {
    hair: "Hair",
    decorations: "Decorations",
    others: "Others",
  },
  emptyCategory: "No items in this category yet. Check back soon.",
  whereToBuyTitle: "Where to buy in Eswatini",
  visitShop: "Visit online shop",
  openInMaps: "Open in Google Maps",
  detailClose: "Close",
  footerNote: "© Anpeng Trading — Salon Catalogue",
  admin: {
    title: "Salon Admin",
    loginPrompt: "Sign in to manage the salon catalogue.",
    continueWithGoogle: "Continue with Google",
    signOut: "Sign out",
    products: "Products",
    shops: "Where to buy",
    addProduct: "Add product",
    addShop: "Add shop",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    publish: "Publish",
    unpublish: "Unpublish",
    published: "Published",
    draft: "Draft",
    fieldName: "Name",
    fieldCategory: "Category",
    fieldDescription: "Description",
    fieldPrice: "Price",
    fieldCurrency: "Currency",
    fieldPhotos: "Photos",
    coverHint: "First photo is the cover.",
    shopName: "Shop name",
    onlineUrl: "Online shop URL",
    mapAddress: "Address",
    googleMapsUrl: "Google Maps URL",
  },
} as const;

export default SALON_COPY;
